# Server Configuration
server.port=8082
spring.application.name=main-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/dinemaster_main

# CORS Configuration
cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Logging
logging.level.com.dinemaster.main=DEBUG

# Razorpay Configuration
razorpay.key.id=rzp_test_T0DYTF45Ar9eUL
razorpay.key.secret=86y2vVXSEk3aR3Li7qmICuZp

# AWS Configuration
aws.region=ap-south-1
aws.access-key=AKIARDEUIHDEBZG64IGB
aws.secret-key=YOUR_REAL_SECRET_KEY_HERE
aws.s3.bucket-name=dinemaster-menu-images-yourname123
aws.sns.topic-arn=arn:aws:sns:ap-south-1:075472845000:dinemaster-order-notifications
